### ISSUE TITLE
Adição dos demais membros

### ISSUE THREAD

**Issue by vinicius3w** [IF977/InkFlow#1]
Adicionar os demais membros do time no repositório bem como no Time criado na organização do GitHub.

**Comment by arthurnfarias** [comment]
Já enviei o convite pra eles..
não entendi essa de "Time na organização do GitHub"

**Comment by DenioBBB** [comment]
Seria mais uma organizada de como será o time e registrar isso com uma estrutura mais organizada e definida dentro do github, basicamente seria definir bem os papéis.
